name: launcher

on: push

permissions:
  contents: write

concurrency: launcher

jobs:
  build_launcher:
    if: github.ref_type == 'tag'
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cx_Freeze
          pip install -r requirements.txt

      - name: Freeze app
        run: |
          cd launcher
          cxfreeze build --target-dir=dist

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          path: "launcher/dist"
          filename: "iRefined-Launcher-${{ github.ref_name }}.zip"
          exclusions: "frozen_application_license.txt"

      - name: Release launcher
        uses: softprops/action-gh-release@v2
        with:
          files: "iRefined-Launcher-${{ github.ref_name }}.zip"
          name: iRefined Launcher v${{ github.ref_name }}
          body_path: launcher/CHANGELOG.md
