name: launcher

on: push

permissions:
  contents: write

concurrency: launcher

jobs:
  build_launcher:
    if: github.ref_type == 'tag'
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cx_Freeze
          pip install -r requirements.txt
        working-directory: launcher

      - name: Freeze app
        run: |
          cxfreeze build --target-dir=dist
        working-directory: launcher

      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk
          vpk pack -u iRefined -v ${{ github.ref_name }} -p .\dist -o .\release --noPortable --icon icon.ico
          vpk upload github -o .\release --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "iRefined Launcher v${{ github.ref_name }}" --tag ${{ github.ref_name }} --token ${{ secrets.GITHUB_TOKEN }}
        working-directory: launcher

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            **Launcher v${{ github.ref_name }} released! Restart iRefined to get the latest version.**

            [Or grab it here...](<https://github.com/jason-murray/irefined/releases/latest/download/iRefined-win-Setup.exe>)
